// Generator for the fresh "Chatwoot n8n AI support Agent" workflow.
// Run: node build_workflow.js
// Output: C:\Users\HP\Downloads\Chatwoot_n8n_AI_Support_Agent.json
'use strict';
const fs = require('fs');
const path = require('path');

// ─────────── Credentials reused from existing workflow ───────────
const CRED = {
  chatwoot:     { id: 'SbmBMJv7nxEADt7f', name: 'chatwoot token' },
  fvStore:      { id: 'Z9VqzrucTtbl9lZu', name: 'FV store connect' },
  googleSheets: { id: '33OaFvyrcaNWPBsR', name: 'Google Sheets account 2' },
  openai:       { id: 'oa8lM6ASGY5Ot8g8', name: 'Chatwoot open ai token' }
};
const SHEET_ID  = '1GCl-6QwyPEYiN41LNUIHZaXeZ6mEpFopYM0cZzfZKsI';
const SHEET_TAB = 'FV_live_product';

// ─────────── jsCode blocks (no ES6 template literals → no escaping pain) ───────────
const NORMALIZE_CODE = [
  "const item = $input.first().json;",
  "const body = item.body || item;",
  "const trim = v => String(v == null ? '' : v).trim();",
  "",
  "const content     = trim(body.content);",
  "const senderType  = (body.sender && body.sender.type) || body.sender_type || (body.conversation && body.conversation.meta && body.conversation.meta.sender && body.conversation.meta.sender.type) || '';",
  "const messageType = body.message_type;",
  "const isIncoming  = messageType === 'incoming' || messageType === 0 || messageType === '0';",
  "const isPrivate   = Boolean(body.private);",
  "",
  "const shouldProcess = body.event === 'message_created'",
  "  && isIncoming",
  "  && senderType === 'contact'",
  "  && !isPrivate",
  "  && content.length > 0;",
  "",
  "// Order ID detection",
  "const rxBefore  = /(?:order|pedido|encomenda|n[uú]mero)\\D{0,15}(\\d{4,})\\b/i;",
  "const rxAfter   = /\\b(\\d{5,})\\D{0,15}(?:order|pedido|encomenda|status)/i;",
  "const rxHash    = content.match(/(?:^|\\s)#(\\d{4,})\\b/);",
  "const rxAlone   = content.match(/^\\s*(\\d{5,})\\s*$/);",
  "const rxBeforeM = content.match(rxBefore);",
  "const rxAfterM  = content.match(rxAfter);",
  "const detectedOrderId = (rxBeforeM && rxBeforeM[1])",
  "  || (rxAfterM && rxAfterM[1])",
  "  || (rxHash && rxHash[1])",
  "  || (rxAlone && rxAlone[1])",
  "  || '';",
  "",
  "const senderEmail = trim((body.sender && body.sender.email) || (body.conversation && body.conversation.meta && body.conversation.meta.sender && body.conversation.meta.sender.email) || '');",
  "const senderName  = trim((body.sender && body.sender.name)  || (body.conversation && body.conversation.meta && body.conversation.meta.sender && body.conversation.meta.sender.name)  || '');",
  "const senderPhone = trim((body.sender && body.sender.phone_number) || (body.conversation && body.conversation.meta && body.conversation.meta.sender && body.conversation.meta.sender.phone_number) || '');",
  "",
  "return {",
  "  route: shouldProcess ? 'process' : 'ignore',",
  "  event: body.event || '',",
  "  conversationId: (body.conversation && body.conversation.id) || body.conversation_id || null,",
  "  accountId: (body.account && body.account.id) || body.account_id || null,",
  "  inboxId: (body.inbox && body.inbox.id) || body.inbox_id || (body.conversation && body.conversation.inbox_id) || null,",
  "  content,",
  "  senderEmail,",
  "  senderName,",
  "  senderPhone,",
  "  detectedOrderId,",
  "  config: {",
  "    chatwootBaseUrl: 'https://sac.famivita.com',",
  "    wooBaseUrl: 'https://www.famivita.com.br',",
  "    openAiModel: 'gpt-4.1-mini',",
  "    maxConversationMessages: 24,",
  "    shippingApiUrl: 'https://www.famivita.com.br/wp-json/custom-shipping/v1/quote-get',",
  "    defaultItemWeightKg: 0.5",
  "  }",
  "};"
].join('\n');

const BUILD_AI_CODE = [
  "const ctx = $('Normalize Event').first().json;",
  "const convo = $('Get Conversation').first().json || {};",
  "const orderResp = $('Maybe Lookup Order').first().json || {};",
  "const order = orderResp.body || orderResp;",
  "const catalogRaw = $('Get Catalog').all().map(x => x.json).filter(Boolean);",
  "",
  "const stripHtml = v => String(v || '').replace(/<[^>]+>/g,' ').replace(/\\s+/g,' ').trim();",
  "const norm = s => String(s || '').normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').toLowerCase();",
  "",
  "// ── Catalog enrichment ──",
  "const wooBase = ctx.config.wooBaseUrl;",
  "const getCol = (row, ...cands) => {",
  "  for (const c of cands) if (row[c] !== undefined && row[c] !== null) return row[c];",
  "  const keys = Object.keys(row);",
  "  for (const c of cands) {",
  "    const want = String(c).trim().toLowerCase().replace(/[\\s_-]+/g,'');",
  "    const k = keys.find(k => String(k).trim().toLowerCase().replace(/[\\s_-]+/g,'') === want);",
  "    if (k && row[k] !== undefined && row[k] !== null) return row[k];",
  "  }",
  "  return '';",
  "};",
  "const pickPrice = r => String(getCol(r,'price','sale_price','regular_price') || '').trim();",
  "",
  "const catalogEnriched = catalogRaw.map(r => {",
  "  const productId   = Number(getCol(r,'product_id','id') || 0) || null;",
  "  const variationId = Number(getCol(r,'variation_id','var_id') || 0) || null;",
  "  const cartId      = variationId || productId;",
  "  const title       = String(getCol(r,'custom_title','product_title','title','name') || '').trim();",
  "  const altName     = String(getCol(r,'custom_text') || '').trim();",
  "  const extraText   = [getCol(r,'custom_text1'), getCol(r,'custom_text2')].map(v => stripHtml(v||'')).filter(Boolean).join(' ').slice(0,300);",
  "  const stockStatus = String(getCol(r,'stock_status') || '').trim().toLowerCase();",
  "  const isOos = stockStatus === 'outofstock' || stockStatus === 'out_of_stock' || stockStatus === 'out-of-stock';",
  "  const isBackorder = stockStatus === 'onbackorder' || stockStatus === 'on_backorder' || stockStatus === 'on-backorder';",
  "  const titleSuffix = isOos ? ' ❌ ESGOTADO' : (isBackorder ? ' ⏳ Pré-venda' : '');",
  "  const stockLine   = stockStatus ? ('Estoque: ' + stockStatus) : '';",
  "  const addToCart   = (isOos || !cartId) ? '' : (wooBase + '/carrinho-de-compras/?add-to-cart=' + cartId);",
  "  return {",
  "    product_id: productId,",
  "    variation_id: variationId,",
  "    title,",
  "    alt_name: altName,",
  "    sku: String(getCol(r,'product_sku','sku') || '').trim(),",
  "    url: String(getCol(r,'product_url','url') || '').trim(),",
  "    add_to_cart: addToCart,",
  "    price: pickPrice(r),",
  "    short: extraText,",
  "    tags: String(getCol(r,'product_tags','tags') || '').trim(),",
  "    manufacturer: String(getCol(r,'product_manufacturer','manufacturer') || '').trim(),",
  "    weight_kg: Number(getCol(r,'weight_kg','weight') || ctx.config.defaultItemWeightKg) || ctx.config.defaultItemWeightKg,",
  "    status: String(getCol(r,'status') || '').trim().toLowerCase(),",
  "    stock_status: stockStatus,",
  "    title_suffix: titleSuffix,",
  "    stock_line: stockLine",
  "  };",
  "});",
  "",
  "const catalogAll = catalogEnriched",
  "  .filter(p => p.title || p.alt_name)",
  "  .filter(p => !p.status || p.status === 'publish');",
  "",
  "// ── Conversation history (oldest → newest) ──",
  "const rawMsgs = Array.isArray(convo.payload) ? convo.payload",
  "  : (Array.isArray(convo.data && convo.data.payload) ? convo.data.payload",
  "  : (Array.isArray(convo) ? convo : []));",
  "const sorted = rawMsgs",
  "  .filter(m => !m.private && m.message_type !== 'activity' && m.message_type !== 2)",
  "  .sort((a,b) => (a.created_at||0) - (b.created_at||0))",
  "  .slice(-ctx.config.maxConversationMessages);",
  "const history = sorted.map(m => {",
  "  const role = (m.message_type === 'incoming' || m.message_type === 0) ? 'user' : 'assistant';",
  "  return { role, content: stripHtml(m.content || '') };",
  "}).filter(m => m.content);",
  "",
  "// ── Detect price filter from latest user message ──",
  "const lastUserMsg = ((history.filter(m => m.role === 'user').slice(-1)[0]) || { content: '' }).content;",
  "const detectPriceFilter = (msgRaw) => {",
  "  const t = norm(msgRaw);",
  "  const num = g => Number.parseFloat(String(g).replace(/\\./g,'').replace(',', '.')) || 0;",
  "  let m = t.match(/(?:entre|between)\\s+r?\\$?\\s*(\\d+(?:[.,]\\d+)?)\\s+(?:e|and|to|ate)\\s+r?\\$?\\s*(\\d+(?:[.,]\\d+)?)/);",
  "  if (m) return { type: 'range', min: num(m[1]), max: num(m[2]) };",
  "  m = t.match(/(?:abaixo de|menos de|ate|no maximo|max(?:imo)?(?: de)?|below|less than|under|cheaper than|no more than|maximo)\\s+r?\\$?\\s*(\\d+(?:[.,]\\d+)?)/);",
  "  if (m) return { type: 'max', value: num(m[1]) };",
  "  m = t.match(/(?:acima de|mais de|maior que|above|more than|over|at least|pelo menos)\\s+r?\\$?\\s*(\\d+(?:[.,]\\d+)?)/);",
  "  if (m) return { type: 'min', value: num(m[1]) };",
  "  return null;",
  "};",
  "const parsePrice = v => {",
  "  if (typeof v === 'number') return Number.isFinite(v) ? v : 0;",
  "  const s = String(v||'').replace(/[^0-9,.\\-]/g,'').trim();",
  "  if (!s) return 0;",
  "  const cleaned = s.includes(',') && s.includes('.') ? s.replace(/\\./g,'').replace(',', '.') : s.replace(',', '.');",
  "  const n = Number.parseFloat(cleaned);",
  "  return Number.isFinite(n) ? n : 0;",
  "};",
  "const priceFilter = detectPriceFilter(lastUserMsg);",
  "let priceFilteredCatalog = catalogAll;",
  "if (priceFilter) {",
  "  priceFilteredCatalog = catalogAll.filter(p => {",
  "    const price = parsePrice(p.price);",
  "    if (price <= 0) return false;",
  "    if (priceFilter.type === 'max')   return price <= priceFilter.value;",
  "    if (priceFilter.type === 'min')   return price >= priceFilter.value;",
  "    if (priceFilter.type === 'range') return price >= priceFilter.min && price <= priceFilter.max;",
  "    return true;",
  "  });",
  "  if (priceFilter.type === 'max') priceFilteredCatalog.sort((a,b) => parsePrice(a.price) - parsePrice(b.price));",
  "  else if (priceFilter.type === 'min') priceFilteredCatalog.sort((a,b) => parsePrice(b.price) - parsePrice(a.price));",
  "}",
  "",
  "// ── Keyword ranking ──",
  "const STOPWORDS = new Set(['the','and','for','com','para','que','meu','minha','seu','sua','sobre','quero','preciso','send','tell','show','give','need','want','have','this','that','here','there','please','olá','ola','oi','bom','boa','dia','tarde','noite','obrigado','obrigada','por','favor','são','sao','não','nao','sim','também','tambem','muito','mais','menos','tudo','nada','product','products','produto','produtos','detail','details','detalhe','detalhes','gostaria','poderia','sabe','dizer','onde','quanto','como','qual','quais']);",
  "const tokens = norm(lastUserMsg).split(/[^a-z0-9]+/).filter(w => w.length >= 3 && !STOPWORDS.has(w));",
  "const scoreRow = row => {",
  "  if (tokens.length === 0) return 0;",
  "  const titleHay = norm([row.title, row.alt_name].join(' '));",
  "  const otherHay = norm([row.short, row.tags, row.manufacturer, row.sku, row.url].join(' '));",
  "  let s = 0;",
  "  for (const t of tokens) {",
  "    if (titleHay.includes(t)) s += 3;",
  "    else if (otherHay.includes(t)) s += 1;",
  "  }",
  "  return s;",
  "};",
  "let scored = priceFilteredCatalog.map(r => ({ row: r, score: scoreRow(r) }));",
  "scored.sort((a,b) => b.score - a.score);",
  "const VISIBLE_LIMIT = 100;",
  "let catalog = scored.slice(0, VISIBLE_LIMIT).map(s => s.row);",
  "",
  "// ── Fallback: if price filter eliminated everything, show closest options ──",
  "// Without this, the AI gets an empty catalog and may return empty reply.",
  "let priceFilterEmptied = false;",
  "if (catalog.length === 0 && catalogAll.length > 0) {",
  "  priceFilterEmptied = Boolean(priceFilter);",
  "  const fallback = catalogAll.slice().sort((a,b) => parsePrice(a.price) - parsePrice(b.price));",
  "  catalog = fallback.slice(0, 30);",
  "}",
  "",
  "// ── Fallback: if keyword scoring and the user clearly meant a search,",
  "//    keep the top-priced items so the AI has options to suggest ──",
  "if (catalog.length === 0 && catalogAll.length > 0) {",
  "  catalog = catalogAll.slice(0, 30);",
  "}",
  "",
  "// ── Detect active order item from prior assistant messages ──",
  "let activeOrderItem = null;",
  "const recentAssistant = history.filter(m => m.role === 'assistant').slice(-4);",
  "for (let i = recentAssistant.length - 1; i >= 0; i--) {",
  "  const msg = recentAssistant[i].content || '';",
  "  const safeIds = [];",
  "  let mm; const rx = /add-to-cart=(\\d+)/g;",
  "  while ((mm = rx.exec(msg)) !== null) safeIds.push(Number(mm[1]));",
  "  if (safeIds.length === 1) {",
  "    const id = safeIds[0];",
  "    const cat = catalogAll.find(p => Number(p.variation_id) === id || Number(p.product_id) === id);",
  "    if (cat) {",
  "      activeOrderItem = { product_id: cat.product_id, variation_id: cat.variation_id, title: cat.title, price: cat.price, stock_status: cat.stock_status };",
  "      break;",
  "    }",
  "  } else if (safeIds.length > 1) {",
  "    break; // ambiguous — let the AI decide based on user's selection",
  "  }",
  "}",
  "",
  "// ── User picked an explicit option number (1, 2, 3...) ──",
  "// If the prior assistant message numbered options, pull the chosen ID.",
  "const lastUserMsgRaw = lastUserMsg.toLowerCase().trim();",
  "const optionMatch = lastUserMsgRaw.match(/^(?:op[cç][aã]o\\s*)?(?:n[uú]?mero\\s*)?(\\d{1,2})\\b/) || lastUserMsgRaw.match(/\\bop[cç][aã]o\\s*(\\d{1,2})\\b/);",
  "if (optionMatch && recentAssistant.length > 0) {",
  "  const idx = Number(optionMatch[1]) - 1;",
  "  const lastAssist = recentAssistant[recentAssistant.length - 1].content || '';",
  "  const ids = [];",
  "  let mm; const rx = /add-to-cart=(\\d+)/g;",
  "  while ((mm = rx.exec(lastAssist)) !== null) ids.push(Number(mm[1]));",
  "  if (idx >= 0 && idx < ids.length) {",
  "    const cat = catalogAll.find(p => Number(p.variation_id) === ids[idx] || Number(p.product_id) === ids[idx]);",
  "    if (cat) activeOrderItem = { product_id: cat.product_id, variation_id: cat.variation_id, title: cat.title, price: cat.price, stock_status: cat.stock_status };",
  "  }",
  "}",
  "",
  "// ── Variation attribute override ──",
  "// If the customer's recent message specifies an attribute (60g, 168 cápsulas,",
  "// 12 semanas, etc.) that doesn't match the current AOI's title, switch AOI to",
  "// the matching variation in the same product family.",
  "{",
  "  const ATTR_RX = /\\b(\\d+\\s*(?:g|ml|mg|kg|l|c[aá]psulas?|cap|comprimidos?|sach[eê]s?|tiras?|semanas?|meses?|unidades?|pares?|aplicadores?))\\b/gi;",
  "  const recentUserMsgs = history.filter(m => m.role === 'user').slice(-3);",
  "  let userAttrs = [];",
  "  for (let i = recentUserMsgs.length - 1; i >= 0; i--) {",
  "    const msg = recentUserMsgs[i].content || '';",
  "    const matches = [];",
  "    let am;",
  "    ATTR_RX.lastIndex = 0;",
  "    while ((am = ATTR_RX.exec(msg.toLowerCase())) !== null) {",
  "      matches.push(am[1].replace(/\\s+/g, '').toLowerCase());",
  "    }",
  "    if (matches.length > 0) { userAttrs = matches; break; }",
  "  }",
  "  if (userAttrs.length > 0) {",
  "    const titleHasAll = (cat, attrs) => {",
  "      const t = norm(cat.title).replace(/\\s+/g, '');",
  "      return attrs.every(a => t.includes(a));",
  "    };",
  "    const aoiOk = activeOrderItem && titleHasAll(activeOrderItem, userAttrs);",
  "    if (!aoiOk) {",
  "      let candidates = activeOrderItem",
  "        ? catalogAll.filter(p => Number(p.product_id) === Number(activeOrderItem.product_id))",
  "        : catalogAll;",
  "      let better = candidates.find(p => titleHasAll(p, userAttrs));",
  "      if (!better && activeOrderItem) better = catalogAll.find(p => titleHasAll(p, userAttrs));",
  "      if (better) {",
  "        activeOrderItem = {",
  "          product_id: better.product_id,",
  "          variation_id: better.variation_id,",
  "          title: better.title,",
  "          price: better.price,",
  "          stock_status: better.stock_status",
  "        };",
  "      }",
  "    }",
  "  }",
  "}",
  "",
  "// ── Identity keys for workflow memory + ORDER_INFO ownership filter ──",
  "const ownerEmail = String(ctx.senderEmail || '').trim().toLowerCase();",
  "const ownerPhoneDigits = String(ctx.senderPhone || '').replace(/\\D/g, '');",
  "const ownerPhoneTail = ownerPhoneDigits.slice(-10);",
  "const memoryKey = (ownerPhoneTail && ownerPhoneTail.length >= 8)",
  "  ? ('p:' + ownerPhoneTail)",
  "  : (ownerEmail ? ('e:' + ownerEmail) : '');",
  "",
  "// ── Read previousBilling from workflow memory (static data) ──",
  "// Saved by Build Order Confirmation after a successful order. Persists across",
  "// executions inside this workflow's settings JSON.",
  "let previousBilling = null;",
  "try {",
  "  const staticData = $getWorkflowStaticData('global');",
  "  const memory = staticData.billingMemory || {};",
  "  if (memoryKey && memory[memoryKey]) {",
  "    const saved = memory[memoryKey];",
  "    if (saved && saved.billing_postcode && saved.billing_address_1 && saved.billing_city) {",
  "      previousBilling = saved;",
  "    }",
  "  }",
  "} catch (e) { /* static data unavailable — fall through with null */ }",
  "",
  "// ── Order context (status questions only — filtered to current contact) ──",
  "const isOwnerOrder = (o) => {",
  "  if (!o || !o.billing) return false;",
  "  const e = String(o.billing.email || '').trim().toLowerCase();",
  "  if (ownerEmail && e && e === ownerEmail) return true;",
  "  if (ownerPhoneTail && ownerPhoneTail.length >= 8) {",
  "    const p = String(o.billing.phone || '').replace(/\\D/g, '').slice(-10);",
  "    if (p && p === ownerPhoneTail) return true;",
  "  }",
  "  return false;",
  "};",
  "let orderInfo = null;",
  "if (Array.isArray(order)) {",
  "  const ownOrders = order.filter(isOwnerOrder);",
  "  if (ownOrders.length > 0) {",
  "    orderInfo = { kind: 'list', orders: ownOrders.slice(0,5).map(o => ({",
  "      id: o.id, status: o.status, total: o.total, date: o.date_created,",
  "      pay_url: o.payment_url || '', items: (o.line_items||[]).map(i => i.name)",
  "    })) };",
  "  }",
  "} else if (order && order.id && isOwnerOrder(order)) {",
  "  orderInfo = { kind: 'single', order: {",
  "    id: order.id, status: order.status, total: order.total,",
  "    date: order.date_created, pay_url: order.payment_url || '',",
  "    items: (order.line_items||[]).map(i => ({ name: i.name, qty: i.quantity, total: i.total })),",
  "    shipping_total: order.shipping_total, billing_email: (order.billing && order.billing.email)",
  "  }};",
  "}",
  "",
  "// ── System prompt ──",
  "const systemMessage = [",
  "  'Você é uma atendente humana brasileira via WhatsApp para a Famivita (famivita.com.br), loja de bem-estar feminino.',",
  "  'Fale natural, calorosa, em PT-BR. Use mensagens curtas (2-4 frases) e emojis com moderação. NUNCA diga que é IA, robô ou bot.',",
  "  '',",
  "  '═══════════ REGRAS CRÍTICAS ═══════════',",
  "  '1. SEMPRE leia o histórico completo antes de responder. Nunca repita perguntas já respondidas.',",
  "  '2. Saída SEMPRE em JSON estrito. Nada de texto fora do JSON.',",
  "  '3. NUNCA invente nomes, IDs, preços ou URLs de produto. Use APENAS os valores do CATÁLOGO abaixo.',",
  "  '4. NUNCA construa nem modifique URLs. Copie os campos url e add_to_cart letra por letra.',",
  "  '5. SEMPRE escreva algo no campo \"reply\" — NUNCA retorne reply vazio. Mesmo se o CATÁLOGO estiver vazio (filtro de preço sem resultados, busca sem match), escreva uma frase explicando isso. Ex.: \"Hmm, não encontrei produtos com esse preço. Quer ver as opções mais em conta?\" ou \"Não consegui localizar esse produto. Pode me dizer o nome de outra forma?\".',",
  "  '',",
  "  '═══════════ MOSTRAR PRODUTOS ═══════════',",
  "  'Para mostrar produtos você DEVE fazer EXATAMENTE assim:',",
  "  '  1. Inclua a chave \"show_products\" no JSON: array de variation_id (ou product_id quando não houver variação) extraídos do CATÁLOGO.',",
  "  '  2. Coloque o token literal {PRODUCTS} dentro do campo \"reply\", no ponto onde os produtos devem aparecer.',",
  "  '  3. NÃO escreva nomes, preços, links ou status de estoque dos produtos no \"reply\" — o sistema renderiza tudo automaticamente, numerado 1., 2., 3....',",
  "  '  4. ⚠️ LIMITE DE 6 PRODUTOS por mensagem. WhatsApp tem limite de 4096 caracteres por mensagem; mais que 6 produtos faz a mensagem ser rejeitada e o cliente NÃO vê nada. Se houver muitas opções relevantes, escolha as 6 melhores e mencione \"tenho mais opções, é só pedir\".',",
  "  '',",
  "  '🛑 ABSOLUTO — NUNCA ESCREVA ENDEREÇO INLINE NO REPLY:',",
  "  '  NUNCA escreva o endereço do cliente numa linha só do tipo \"Rua X, nº 1, Bairro, Cidade/UF, CEP 00000-000\" dentro do reply. SEMPRE que precisar mostrar o endereço, vá direto para action_after=\"calculate_shipping\" — o sistema gera o resumo completo (Itens, Entrega com cada campo em linha separada Email/CEP/Endereço/Número/Bairro/Cidade/Estado/CPF/Telefone, Frete, Total) automaticamente.',",
  "",
  "  '🛑 ABSOLUTO — TROCA DE PRODUTO DURANTE FLUXO DE PEDIDO:',",
  "  '  Se o cliente já viu um preview e disser \"trocar produto\", \"mudar para X\", \"i need Y now\", \"preciso de Z\", etc., trate como nova intenção de pedido. Ponha items=[novo_produto] e action_after=\"calculate_shipping\". NÃO pergunte \"posso confirmar o endereço?\" — só rode calculate_shipping com o novo produto + os mesmos billing_* da PREVIOUS_BILLING. O cliente vê o preview novo (com novo produto, novo frete) e confirma a partir dele.',",
  "",
  "  '🛑 ABSOLUTO — NUNCA ESCREVA O RODAPÉ DE PEDIDO:',",
  "  '  O sistema adiciona automaticamente, abaixo dos produtos, um rodapé com:',",
  "  '    \"💬 Quer pedir por aqui mesmo pelo WhatsApp? Me diga a opção 1, 2, 3... e envie seus dados de cobrança no formato: Email, CEP, Endereço...\"',",
  "  '  VOCÊ NÃO DEVE escrever esse rodapé, nem qualquer variação dele (\"Quer pedir...\", \"Me diga a opção 1, 2\", \"envie seus dados de cobrança\", o template \"Email: ... CEP: ... Endereço: ...\"). O sistema cuida disso. Se você escrever, o cliente verá em duplicado.',",
  "  '  Termine seu \"reply\" logo após o token {PRODUCTS}, sem instrução adicional sobre como pedir.',",
  "  '',",
  "  'Quando o cliente NÃO está pedindo para ver produtos (ex.: já está mandando dados de cobrança, confirmando pedido, perguntando sobre status), use show_products = [] e NÃO inclua {PRODUCTS}.',",
  "  '',",
  "  'VARIAÇÕES: o catálogo tem uma linha por variação (cada uma com seu variation_id e add_to_cart). Mostre cada variação como item próprio. Se o cliente especificar atributo (\"60g\", \"168 cápsulas\"), encontre a linha cujo título contenha família + atributo. Quando em dúvida, pergunte qual variação ele quer.',",
  "  '',",
  "  'ESTOQUE: para LISTAGEM, inclua produtos de TODOS os status (instock/outofstock/onbackorder) — o sistema marca cada um corretamente. Para PEDIDO, NUNCA inclua produto outofstock em items[].',",
  "  '',",
  "  '═══════════ FLUXO DE PEDIDO VIA WHATSAPP ═══════════',",
  "  'STAGE 0 — VERIFICAÇÃO DE ESTOQUE:',",
  "  '  Antes de qualquer outra coisa quando o cliente quer pedir um produto: olhe stock_status no CATÁLOGO.',",
  "  '  Se outofstock → recuse o pedido e ofereça similares em estoque. action_after = \"none\".',",
  "  '  Se instock → siga para STAGE 1.',",
  "  '',",
  "  'STAGE 1 — DADOS DE COBRANÇA:',",
  "  '  Campos necessários (8): email, cpf, postcode (CEP), address_1 (rua), number, neighborhood (bairro), city, state (UF). Nome e telefone vêm do CUSTOMER_PROFILE.',",
  "  '  ',",
  "  '  ⭐ Se PREVIOUS_BILLING (mais abaixo) NÃO for null:',",
  "  '    O cliente já tem endereço cadastrado. NÃO peça os dados de novo, e NÃO pergunte \"Posso confirmar o endereço?\" antes do preview.',",
  "  '    🚀 Quando o cliente expressa intenção de pedido (\"want to order X\", \"quero pedir Y\", \"fazer o pedido\"), vá DIRETO para action_after=\"calculate_shipping\" com items=[{product_id, variation_id, quantity}] e todos os billing_* preenchidos com PREVIOUS_BILLING. O sistema vai gerar o resumo completo com itens, endereço, frete e total — o cliente confirma a partir desse resumo.',",
  "  '    Se o cliente quiser alterar APENAS um ou poucos campos antes de pedir, peça SOMENTE esses campos.',",
  "  '    Se o cliente quiser trocar todo o endereço, peça os 8 campos.',",
  "  '  ',",
  "  '  Se PREVIOUS_BILLING for null:',",
  "  '    Cliente novo — peça os 8 campos em uma única mensagem curta. action_after = \"none\".',",
  "  '',",
  "  'STAGE 2 — PRÉ-VISUALIZAÇÃO COM FRETE:',",
  "  '  Quando todos os campos estiverem preenchidos E o produto escolhido for in-stock:',",
  "  '  action_after = \"calculate_shipping\"',",
  "  '  action_data com items=[{product_id, variation_id, quantity}] e billing_*.',",
  "  '  reply = string curta tipo \"Um instante, calculando o frete...\". O sistema substitui pelo preview formatado.',",
  "  '',",
  "  'STAGE 3 — CONFIRMAÇÃO:',",
  "  '  Cliente confirma com \"sim\", \"confirmo\", \"pode fechar\":',",
  "  '  action_after = \"create_order\"',",
  "  '  action_data com todos os billing_*, items[], shipping_method, shipping_cost.',",
  "  '  reply curto tipo \"Ótimo, gerando seu pedido...\". O sistema anexa o link de pagamento.',",
  "  '',",
  "  '⚠️ PROTOCOLO DE PRÉ-VISUALIZAÇÃO (CRÍTICO):',",
  "  '  Sempre que QUALQUER campo de cobrança/endereço mudar APÓS uma pré-visualização já mostrada (cliente trocou CEP, endereço, número, bairro, cidade, estado, etc.), você DEVE rodar calculate_shipping novamente ANTES de aceitar create_order.',",
  "  '  NUNCA pule de \"mudei meu CEP\" direto para create_order — o frete e o total mudam quando o CEP muda, e o cliente precisa ver o novo resumo antes de confirmar.',",
  "  '  Fluxo correto: cliente muda CEP → você roda calculate_shipping (novo preview com novo frete) → cliente confirma → você roda create_order.',",
  "  '',",
  "  '═══════════ STATUS DE PEDIDO ═══════════',",
  "  'Se o cliente perguntar sobre pedido existente, use ORDER_INFO. Traduza status:',",
  "  '  pending → Aguardando pagamento (NÃO concluído)',",
  "  '  processing → Em processamento (pagamento confirmado)',",
  "  '  on-hold → Em espera   |   completed → Concluído / entregue',",
  "  '  cancelled → Cancelado |   refunded → Reembolsado |   failed → Falhou',",
  "  'Inclua pay_url quando status for pending ou on-hold.',",
  "  'Se ORDER_INFO for null, peça o número do pedido ou o e-mail cadastrado.',",
  "  '',",
  "  '═══════════ ESQUEMA JSON DE SAÍDA ═══════════',",
  "  '{',",
  "  '  \"reply\": \"string em PT-BR; use {PRODUCTS} onde os produtos devem aparecer\",',",
  "  '  \"show_products\": [594247, 1044937],',",
  "  '  \"action_after\": \"none\" | \"calculate_shipping\" | \"create_order\",',",
  "  '  \"action_data\": {',",
  "  '    \"items\": [{ \"product_id\": 12345, \"variation_id\": 58, \"quantity\": 1 }],',",
  "  '    \"billing_name\": \"...\",',",
  "  '    \"billing_email\": \"...\",',",
  "  '    \"billing_cpf\": \"...\",',",
  "  '    \"billing_phone\": \"...\",',",
  "  '    \"billing_postcode\": \"...\",',",
  "  '    \"billing_address_1\": \"...\",',",
  "  '    \"billing_number\": \"...\",',",
  "  '    \"billing_neighborhood\": \"...\",',",
  "  '    \"billing_city\": \"...\",',",
  "  '    \"billing_state\": \"...\",',",
  "  '    \"shipping_method\": \"PAC\",',",
  "  '    \"shipping_cost\": 0',",
  "  '  }',",
  "  '}',",
  "  'Use action_data = {} e show_products = [] quando não aplicável.',",
  "  '',",
  "  '═══════════ ITEM ATIVO DETECTADO ═══════════',",
  "  activeOrderItem ? JSON.stringify(activeOrderItem) : 'null',",
  "  '',",
  "  '═══════════ CATÁLOGO (' + catalog.length + ' produtos) ═══════════',",
  "  priceFilterEmptied",
  "    ? '(NENHUM produto se encaixa exatamente no filtro de preço pedido. O CATÁLOGO abaixo mostra as opções MAIS PRÓXIMAS em estoque. Ao responder, deixe claro que não achou produtos exatamente naquela faixa e ofereça as alternativas mais em conta.)'",
  "    : '',",
  "  JSON.stringify(catalog),",
  "  '',",
  "  '═══════════ ORDER_INFO ═══════════',",
  "  orderInfo ? JSON.stringify(orderInfo) : 'null',",
  "  '',",
  "  '═══════════ PREVIOUS_BILLING ═══════════',",
  "  '(Endereço e dados salvos do pedido anterior do cliente. Use como PADRÃO — não peça os dados de novo.)',",
  "  '(Se o cliente quiser alterar algum campo, ele dirá explicitamente; troque APENAS aquele campo.)',",
  "  '(Se PREVIOUS_BILLING for null, peça os 8 campos via Stage 1 normalmente.)',",
  "  previousBilling ? JSON.stringify(previousBilling) : 'null',",
  "  '',",
  "  '═══════════ CUSTOMER_PROFILE ═══════════',",
  "  JSON.stringify({ name: ctx.senderName, email: ctx.senderEmail, phone: ctx.senderPhone })",
  "].join('\\n');",
  "",
  "const messages = [{ role: 'system', content: systemMessage }].concat(history);",
  "",
  "return {",
  "  accountId: ctx.accountId,",
  "  conversationId: ctx.conversationId,",
  "  chatwootBaseUrl: ctx.config.chatwootBaseUrl,",
  "  wooBaseUrl: ctx.config.wooBaseUrl,",
  "  shippingApiUrl: ctx.config.shippingApiUrl,",
  "  defaultItemWeightKg: ctx.config.defaultItemWeightKg,",
  "  senderName: ctx.senderName,",
  "  senderEmail: ctx.senderEmail,",
  "  senderPhone: ctx.senderPhone,",
  "  activeOrderItem,",
  "  previousBilling,",
  "  catalog,",
  "  openAiRequest: {",
  "    model: ctx.config.openAiModel,",
  "    temperature: 0.3,",
  "    max_tokens: 1500,",
  "    response_format: { type: 'json_object' },",
  "    messages",
  "  }",
  "};"
].join('\n');

const PARSE_AI_CODE = [
  "const ctx = $('Build AI Request').first().json;",
  "const aiResp = $input.first().json || {};",
  "const aiBody = aiResp.body || aiResp;",
  "const raw = (aiBody && aiBody.choices && aiBody.choices[0] && aiBody.choices[0].message && aiBody.choices[0].message.content) || '';",
  "",
  "let parsed = { reply: '', action_after: 'none', action_data: {}, show_products: [] };",
  "try { parsed = JSON.parse(raw); } catch (e) {",
  "  parsed = { reply: String(raw).trim() || 'Olá! Como posso ajudar?', action_after: 'none', action_data: {}, show_products: [] };",
  "}",
  "",
  "let reply = String(parsed.reply || '').trim();",
  "const intendedAction = String(parsed.action_after || 'none').toLowerCase();",
  "const data = parsed.action_data || {};",
  "",
  "// ── Render product blocks (numbered, deterministic) ──",
  "// Cap at 6 — WhatsApp text-message hard limit is 4096 chars. Each product",
  "// block is ~250-300 chars. Beyond 6 products + footer, the message gets",
  "// rejected by WhatsApp and the customer sees nothing.",
  "const MAX_PRODUCTS_PER_TURN = 6;",
  "const showIdsRaw = Array.isArray(parsed.show_products) ? parsed.show_products : [];",
  "const showIds = showIdsRaw.slice(0, MAX_PRODUCTS_PER_TURN);",
  "const showIdsTruncated = showIdsRaw.length > MAX_PRODUCTS_PER_TURN;",
  "const renderBlock = (cat, idx) => {",
  "  if (!cat) return null;",
  "  const lines = [];",
  "  const priceText = cat.price ? ('R$ ' + String(cat.price).replace('.', ',')) : '';",
  "  lines.push('*' + (idx+1) + '. ' + cat.title + '*' + (priceText ? ' — ' + priceText : '') + (cat.title_suffix || ''));",
  "  if (cat.stock_line) lines.push(cat.stock_line);",
  "  if (cat.url) lines.push('Saiba mais: ' + cat.url);",
  "  if (cat.add_to_cart) lines.push('Comprar agora: ' + cat.add_to_cart);",
  "  return lines.join('\\n');",
  "};",
  "let productsRendered = 0;",
  "if (showIds.length > 0) {",
  "  const blocks = showIds.map((id, i) => {",
  "    const cat = (ctx.catalog || []).find(p => Number(p.variation_id) === Number(id) || Number(p.product_id) === Number(id));",
  "    return renderBlock(cat, i);",
  "  }).filter(Boolean);",
  "  productsRendered = blocks.length;",
  "  let productsText = blocks.join('\\n\\n');",
  "  if (showIdsTruncated) {",
  "    productsText += '\\n\\n_(Tenho mais opções — me diga \"ver mais\" se quiser ver outras.)_';",
  "  }",
  "  reply = reply.indexOf('{PRODUCTS}') !== -1",
  "    ? reply.split('{PRODUCTS}').join(productsText)",
  "    : (productsText ? (reply + (reply ? '\\n\\n' : '') + productsText) : reply);",
  "}",
  "",
  "// ── Strip any AI-written variant of our order-via-whatsapp footer ──",
  "// The AI sometimes copies the footer text into its own reply, which then",
  "// duplicates with the system-appended footer. Remove anything from the first",
  "// 'Quer pedir por aqui' marker to end-of-reply.",
  "{",
  "  const stripPatterns = [",
  "    /\\s*[^\\n]*?💬\\s*\\*?\\s*Quer pedir por aqui mesmo[\\s\\S]*$/i,",
  "    /\\n[^\\n]*Quer pedir por aqui mesmo[\\s\\S]*$/i,",
  "    /\\s+Me diga a \\*?op[cç][aã]o\\s*1\\s*,\\s*2[\\s\\S]*$/i,",
  "    /\\n\\s*Email:\\s*seu@email\\.com[\\s\\S]*$/i",
  "  ];",
  "  for (const rx of stripPatterns) reply = reply.replace(rx, '');",
  "  reply = reply.replace(/\\s+$/, '');",
  "}",
  "",
  "// ── Append the order-via-whatsapp footer ONLY for multi-product search lists ──",
  "// Single-product cards (during ordering / billing-info turn) skip the footer to",
  "// avoid the redundant 'opção 1, 2, 3' hint when there's only one option.",
  "const inOrderingFlow = Boolean(ctx.activeOrderItem) || (data && data.items && data.items.length > 0);",
  "const alreadyHasFooter = /quer pedir por aqui mesmo/i.test(reply);",
  "if (productsRendered >= 2 && intendedAction === 'none' && !inOrderingFlow && !alreadyHasFooter) {",
  "  const prev = ctx.previousBilling || null;",
  "  const hasSavedAddress = prev && String(prev.billing_postcode || '').trim() && String(prev.billing_address_1 || '').trim();",
  "  let footerLines;",
  "  if (hasSavedAddress) {",
  "    const phoneFromProfile = String(ctx.senderPhone || '').trim();",
  "    const labeled = [",
  "      ['Email', prev.billing_email],",
  "      ['CEP', prev.billing_postcode],",
  "      ['Endereço', prev.billing_address_1],",
  "      ['Número', prev.billing_number],",
  "      ['Bairro', prev.billing_neighborhood],",
  "      ['Cidade', prev.billing_city],",
  "      ['Estado (UF)', prev.billing_state],",
  "      ['CPF', prev.billing_cpf],",
  "      ['Telefone', prev.billing_phone || phoneFromProfile]",
  "    ].filter(p => String(p[1] || '').trim()).map(p => p[0] + ': ' + String(p[1]).trim());",
  "    footerLines = [",
  "      '',",
  "      '💬 *Quer pedir por aqui mesmo pelo WhatsApp?*',",
  "      'Me diga a *opção 1, 2, 3...* (ou o nome do produto) e eu uso seus dados cadastrados:',",
  "      ''",
  "    ].concat(labeled).concat([",
  "      '',",
  "      '_(Se quiser alterar algum dado ou entregar em outro endereço, é só me avisar.)_'",
  "    ]);",
  "  } else {",
  "    footerLines = [",
  "      '',",
  "      '💬 *Quer pedir por aqui mesmo pelo WhatsApp?*',",
  "      'Me diga a *opção 1, 2, 3...* (ou o nome do produto) e envie seus dados de cobrança no formato:',",
  "      '',",
  "      'Email: seu@email.com',",
  "      'CEP: 00000-000',",
  "      'Endereço: Rua Exemplo',",
  "      'Número: 123',",
  "      'Bairro: Centro',",
  "      'Cidade: São Paulo',",
  "      'Estado (UF): SP',",
  "      'CPF: 000.000.000-00'",
  "    ];",
  "  }",
  "  reply = reply.replace(/\\s+$/, '') + '\\n' + footerLines.join('\\n');",
  "}",
  "",
  "// ── Auto-fill name/phone/email from Chatwoot sender ──",
  "if (!String(data.billing_name||'').trim() && ctx.senderName) data.billing_name = ctx.senderName;",
  "if (!String(data.billing_phone||'').trim() && ctx.senderPhone) data.billing_phone = ctx.senderPhone;",
  "if (!String(data.billing_email||'').trim() && ctx.senderEmail) data.billing_email = ctx.senderEmail;",
  "",
  "// ── Auto-extract billing fields from prior user messages ──",
  "{",
  "  const allUserMsgs = (ctx.openAiRequest && ctx.openAiRequest.messages || [])",
  "    .filter(m => m.role === 'user').map(m => String(m.content || '')).join('\\n');",
  "  const NEXT_LABEL = '(?:\\\\s+(?:e-?mail|cpf|cep|postcode|address|endere[cç]o|rua|street|avenida|number|n[uú]mero|n[º°]|city|cidade|state|estado(?:\\\\s*\\\\(uf\\\\))?|UF|phone|telefone|tel|whatsapp|name|nome(?:\\\\s+completo)?|bairro|neighborhood)\\\\s*[:=])';",
  "  const extractors = [",
  "    ['billing_email', /(?:e-?mail)\\s*[:=]\\s*([\\w.+-]+@[\\w-]+\\.[\\w.-]+)/i],",
  "    ['billing_cpf', /\\b(?:cpf)\\s*[:=]?\\s*([\\d.\\-]{11,18})/i],",
  "    ['billing_postcode', /(?:cep|postcode|c\\.?e\\.?p\\.?)\\s*[:=]?\\s*(\\d{5}-?\\d{3})/i],",
  "    ['billing_address_1', new RegExp('(?:address|endere[cç]o|rua|street|avenida|av\\\\.)\\\\s*[:=]\\\\s*(.+?)(?=' + NEXT_LABEL + '|\\\\s*$)', 'i')],",
  "    ['billing_number', /(?:number|n[uú]mero|n[º°]\\.?)\\s*[:=]?\\s*(\\d{1,8})/i],",
  "    ['billing_neighborhood', new RegExp('(?:bairro|neighborhood)\\\\s*[:=]\\\\s*(.+?)(?=' + NEXT_LABEL + '|\\\\s*$)', 'i')],",
  "    ['billing_city', new RegExp('(?:city|cidade)\\\\s*[:=]\\\\s*(.+?)(?=' + NEXT_LABEL + '|\\\\s*$)', 'i')],",
  "    ['billing_state', /(?:state|estado(?:\\s*\\(uf\\))?|UF)\\s*[:=]?\\s*([A-Z]{2})\\b/i],",
  "    ['billing_phone', /(?:phone|telefone|tel\\.?|whatsapp)\\s*[:=]?\\s*\\+?(\\d[\\d\\s\\-()]{8,20})/i],",
  "    ['billing_name', new RegExp('(?:name|nome(?:\\\\s+completo)?)\\\\s*[:=]\\\\s*(.+?)(?=' + NEXT_LABEL + '|\\\\s*$)', 'i')]",
  "  ];",
  "  for (const pair of extractors) {",
  "    const field = pair[0]; const rx = pair[1];",
  "    if (String(data[field] || '').trim()) continue;",
  "    const m = allUserMsgs.match(rx);",
  "    if (m && m[1]) data[field] = m[1].trim().replace(/[.,;:]+$/, '').trim();",
  "  }",
  "}",
  "",
  "// ── Fall back to PREVIOUS_BILLING (last order) for any still-empty fields ──",
  "// This makes saved billing the default — customer doesn't have to retype.",
  "{",
  "  const prev = ctx.previousBilling || null;",
  "  if (prev) {",
  "    const fields = ['billing_name','billing_email','billing_phone','billing_postcode','billing_address_1','billing_number','billing_neighborhood','billing_city','billing_state','billing_cpf'];",
  "    for (const f of fields) {",
  "      if (!String(data[f] || '').trim() && String(prev[f] || '').trim()) {",
  "        data[f] = prev[f];",
  "      }",
  "    }",
  "  }",
  "}",
  "",
  "// ── Variation guardrail: force items to active order item ──",
  "// IMPORTANT: only fires when the AI's items are in the SAME product family as",
  "// AOI but a different variation (e.g. FamiGel 30g → FamiGel 60g). When the AI",
  "// switches to a DIFFERENT product family (FamiGel → FamiSitol), trust the AI.",
  "const aoi = ctx.activeOrderItem || null;",
  "if (aoi) {",
  "  const aoiVid = Number(aoi.variation_id || 0);",
  "  const aoiPid = Number(aoi.product_id || 0);",
  "  if (Array.isArray(data.items) && data.items.length > 0) {",
  "    const mismatched = data.items.some(it => {",
  "      const vid = Number(it.variation_id || 0);",
  "      const pid = Number(it.product_id || 0);",
  "      // Same family, different variation → force AOI variation.",
  "      if (aoiPid && pid && aoiPid === pid && aoiVid && vid && aoiVid !== vid) return true;",
  "      return false;",
  "    });",
  "    if (mismatched) {",
  "      const qty = Math.max(1, Number(data.items[0].quantity || 1));",
  "      data.items = [{ product_id: aoiPid || undefined, variation_id: aoiVid || undefined, quantity: qty }];",
  "    }",
  "  } else if (intendedAction === 'calculate_shipping' || intendedAction === 'create_order') {",
  "    // AI took an order action but forgot items — inject AOI as fallback",
  "    data.items = [{ product_id: aoiPid || undefined, variation_id: aoiVid || undefined, quantity: 1 }];",
  "  }",
  "}",
  "",
  "// ── Hard guardrails for action ──",
  "const requiredBilling = ['billing_email','billing_postcode','billing_address_1','billing_number','billing_neighborhood','billing_city','billing_state','billing_name','billing_cpf','billing_phone'];",
  "const hasItems = Array.isArray(data.items) && data.items.length > 0 && data.items.every(i => i.product_id || i.variation_id);",
  "const missingFields = requiredBilling.filter(f => !String(data[f]||'').trim());",
  "const hasAllBilling = missingFields.length === 0;",
  "",
  "const itemsWithStock = (data.items || []).map(i => {",
  "  const cat = (ctx.catalog || []).find(p =>",
  "    (i.variation_id && Number(p.variation_id) === Number(i.variation_id)) ||",
  "    (i.product_id && Number(p.product_id) === Number(i.product_id))",
  "  );",
  "  return { item: i, row: cat, oos: cat && cat.stock_status === 'outofstock' };",
  "});",
  "const oosItems = itemsWithStock.filter(x => x.oos);",
  "const hasOos = oosItems.length > 0;",
  "",
  "let resolvedAction = 'none';",
  "if (intendedAction === 'calculate_shipping' && hasItems && hasAllBilling && !hasOos) resolvedAction = 'calculate_shipping';",
  "else if (intendedAction === 'create_order' && hasItems && hasAllBilling && !hasOos) resolvedAction = 'create_order';",
  "",
  "// ── Force fresh preview if billing changed since last preview ──",
  "if (resolvedAction === 'create_order') {",
  "  const prevAssistMsgs = ((ctx.openAiRequest && ctx.openAiRequest.messages) || [])",
  "    .filter(m => m.role === 'assistant').map(m => String(m.content || ''));",
  "  let lastPreview = '';",
  "  for (let i = prevAssistMsgs.length - 1; i >= 0; i--) {",
  "    const m = prevAssistMsgs[i];",
  "    if (/Posso confirmar e gerar o link de pagamento/i.test(m)",
  "        || /Aqui est[áa] o resumo do seu pedido/i.test(m)) {",
  "      lastPreview = m; break;",
  "    }",
  "  }",
  "  if (lastPreview) {",
  "    const STOP = '(?=\\\\s+(?:Email|E-?mail|CEP|Endere[cç]o|N[uú]mero|Bairro|Cidade|Estado|CPF|Telefone|Frete|Subtotal|Total|Posso confirmar|Resumo|Entrega|Itens)\\\\b|\\\\s*$)';",
  "    const cap = (label, src) => {",
  "      const rx = new RegExp(label + '\\\\s*[:=]\\\\s*(.+?)' + STOP, 'i');",
  "      const mm = src.match(rx);",
  "      return mm ? mm[1].trim() : '';",
  "    };",
  "    const normCEP = s => String(s || '').replace(/\\D/g, '');",
  "    const normTxt = s => String(s || '').trim().toLowerCase();",
  "    const prev = {",
  "      cep: normCEP(cap('CEP', lastPreview)),",
  "      addr1: normTxt(cap('Endere[cç]o', lastPreview)),",
  "      number: normTxt(cap('N[uú]mero', lastPreview)),",
  "      neighborhood: normTxt(cap('Bairro', lastPreview)),",
  "      city: normTxt(cap('Cidade', lastPreview)),",
  "      state: normTxt(cap('Estado(?:\\\\s*\\\\(UF\\\\))?', lastPreview))",
  "    };",
  "    const cur = {",
  "      cep: normCEP(data.billing_postcode),",
  "      addr1: normTxt(data.billing_address_1),",
  "      number: normTxt(data.billing_number),",
  "      neighborhood: normTxt(data.billing_neighborhood),",
  "      city: normTxt(data.billing_city),",
  "      state: normTxt(data.billing_state)",
  "    };",
  "    let changed = false;",
  "    for (const f of ['cep','addr1','number','neighborhood','city','state']) {",
  "      if (prev[f] && cur[f] && prev[f] !== cur[f]) { changed = true; break; }",
  "    }",
  "    if (changed) {",
  "      resolvedAction = 'calculate_shipping';",
  "      reply = '';",
  "    }",
  "  }",
  "}",
  "",
  "// ── Auto-advance + preview-confirmation promotion ──",
  "// Two paths:",
  "//   A) Customer expressed order intent (\"want to order X\") + has billing → calculate_shipping",
  "//   B) Customer confirmed (\"sim\", \"ok\") AFTER a preview was shown → create_order",
  "{",
  "  const allMessages = ((ctx.openAiRequest && ctx.openAiRequest.messages) || []);",
  "  const lastUser = (allMessages.filter(m => m.role === 'user').slice(-1)[0] || { content: '' }).content.toLowerCase().trim();",
  "  const prevAssistMsgs = allMessages.filter(m => m.role === 'assistant').map(m => String(m.content || ''));",
  "  const lastAssistMsg = prevAssistMsgs[prevAssistMsgs.length - 1] || '';",
  "  // Preview always contains this exact closing phrase. Uniquely identifies a preview turn.",
  "  const recentPreviewExists = /Posso confirmar e gerar o link de pagamento/i.test(lastAssistMsg)",
  "    || /Aqui est[áa] o resumo do seu pedido/i.test(lastAssistMsg)",
  "    || (/Itens/i.test(lastAssistMsg) && /Entrega/i.test(lastAssistMsg) && /Frete/i.test(lastAssistMsg) && /Resumo/i.test(lastAssistMsg));",
  "",
  "  const REUSE = /\\b(same|mesm[oa]s?|previous|anterior(?:es)?|use (?:the )?same|usar (?:os )?mesmos?|same data|same address|os mesmos dados|dados anteriores)\\b/i;",
  "  const SHORT = /^(sim|yes|ok|okay|confirmo|prossiga|pode|continue|proceed|confirma|confirme|fechar|finalizar)[!.\\s]*$/i;",
  "  const ORDER_INTENT = /\\b(want to (?:order|buy|get)|i (?:want|need|would like)|need to (?:order|change|switch)|change (?:to|product to)|switch to|prefiro|preciso de|preciso (?:pedir|trocar|mudar|de)|quero (?:pedir|comprar|encomendar|mudar|trocar)|gostaria de (?:pedir|comprar)|fazer (?:o )?pedido|finalizar (?:o )?pedido|encomendar|pedir esse|fechar (?:o )?pedido|order this|buy this|order \\w+|me d[eê] |send me)\\b/i;",
  "  const isConfirm = REUSE.test(lastUser) || SHORT.test(lastUser);",
  "  const isFreshIntent = ORDER_INTENT.test(lastUser);",
  "",
  "  // Path B (highest priority): preview shown + user confirmed → create_order",
  "  // Field extractors must stop at next field label (not at newlines — those got",
  "  // stripped to spaces by stripHtml).",
  "  if (recentPreviewExists && isConfirm && resolvedAction !== 'create_order' && hasItems && hasAllBilling && !hasOos) {",
  "    const STOP = '(?=\\\\s+(?:Email|E-?mail|CEP|Endere[cç]o|N[uú]mero|Bairro|Cidade|Estado|CPF|Telefone|Frete|Subtotal|Total|Posso confirmar|Resumo|Entrega|Itens)\\\\b|\\\\s*$)';",
  "    const cap = (label, src) => {",
  "      const rx = new RegExp(label + '\\\\s*[:=]\\\\s*(.+?)' + STOP, 'i');",
  "      const mm = src.match(rx);",
  "      return mm ? mm[1].trim() : '';",
  "    };",
  "    const normCEP = s => String(s || '').replace(/\\D/g, '');",
  "    const normTxt = s => String(s || '').trim().toLowerCase();",
  "    const prev = {",
  "      cep: normCEP(cap('CEP', lastAssistMsg)),",
  "      addr1: normTxt(cap('Endere[cç]o', lastAssistMsg)),",
  "      number: normTxt(cap('N[uú]mero', lastAssistMsg)),",
  "      neighborhood: normTxt(cap('Bairro', lastAssistMsg)),",
  "      city: normTxt(cap('Cidade', lastAssistMsg)),",
  "      state: normTxt(cap('Estado(?:\\\\s*\\\\(UF\\\\))?', lastAssistMsg))",
  "    };",
  "    const cur = {",
  "      cep: normCEP(data.billing_postcode),",
  "      addr1: normTxt(data.billing_address_1),",
  "      number: normTxt(data.billing_number),",
  "      neighborhood: normTxt(data.billing_neighborhood),",
  "      city: normTxt(data.billing_city),",
  "      state: normTxt(data.billing_state)",
  "    };",
  "    let same = true;",
  "    for (const f of ['cep','addr1','number','neighborhood','city','state']) {",
  "      if (prev[f] && cur[f] && prev[f] !== cur[f]) { same = false; break; }",
  "    }",
  "    if (same) {",
  "      resolvedAction = 'create_order';",
  "    }",
  "  }",
  "",
  "  // Path A: order intent + billing on file → calculate_shipping (preview)",
  "  if (resolvedAction === 'none' && intendedAction === 'none' && (isConfirm || isFreshIntent) && hasAllBilling) {",
  "    let canAdvance = false;",
  "    if (Array.isArray(data.items) && data.items.length > 0 && data.items.some(i => i.product_id || i.variation_id)) {",
  "      canAdvance = true;",
  "    } else if (aoi && aoi.stock_status === 'instock') {",
  "      data.items = [{ product_id: aoi.product_id, variation_id: aoi.variation_id, quantity: 1 }];",
  "      canAdvance = true;",
  "    }",
  "    if (canAdvance) {",
  "      resolvedAction = 'calculate_shipping';",
  "      reply = '';",
  "    }",
  "  }",
  "}",
  "",
  "// ── If AI tried to act but we blocked it, override reply with concrete asks ──",
  "const wasBlocked = (intendedAction === 'calculate_shipping' || intendedAction === 'create_order') && resolvedAction === 'none';",
  "if (wasBlocked) {",
  "  if (hasOos) {",
  "    const oosTitles = oosItems.map(x => (x.row && x.row.title) || ('Produto #' + (x.item.variation_id || x.item.product_id))).filter(Boolean);",
  "    const list = oosTitles.length === 1 ? ('*' + oosTitles[0] + '*') : oosTitles.map(t => '*' + t + '*').join(', ');",
  "    reply = 'Infelizmente o produto ' + list + ' está esgotado no momento e não consigo gerar o pedido. Posso te mostrar outras opções similares disponíveis em estoque?';",
  "  } else {",
  "    const fieldLabel = {",
  "      billing_email: 'e-mail', billing_postcode: 'CEP', billing_address_1: 'endereço (rua)',",
  "      billing_number: 'número', billing_neighborhood: 'bairro', billing_city: 'cidade',",
  "      billing_state: 'estado (UF)', billing_name: 'nome completo', billing_cpf: 'CPF', billing_phone: 'telefone com DDD'",
  "    };",
  "    const asks = missingFields.map(f => fieldLabel[f]).filter(Boolean);",
  "    if (asks.length > 0) {",
  "      if (asks.length === 1) reply = 'Para finalizar seu pedido, ainda preciso do seu *' + asks[0] + '*. Pode me informar?';",
  "      else { const last = asks.pop(); reply = 'Para finalizar seu pedido, ainda preciso de: ' + asks.join(', ') + ' e *' + last + '*. Pode me informar?'; }",
  "    } else if (!hasItems) reply = 'Por favor, me confirme qual produto e quantidade você quer pedir.';",
  "  }",
  "}",
  "",
  "// ── FINAL GUARD: never send an empty message — Chatwoot would reject it ──",
  "if (!reply || !reply.trim()) {",
  "  reply = 'Hmm, não consegui processar agora. Pode reformular sua pergunta? 🙂';",
  "}",
  "// Strip any literal {PRODUCTS} that the AI left when it didn't actually pass IDs",
  "if (reply.indexOf('{PRODUCTS}') !== -1) {",
  "  reply = reply.split('{PRODUCTS}').join('').replace(/\\n{3,}/g, '\\n\\n').trim();",
  "  if (!reply) reply = 'Hmm, não consegui localizar esse produto. Pode me dizer o nome de outra forma? 🙂';",
  "}",
  "",
  "return {",
  "  accountId: ctx.accountId,",
  "  conversationId: ctx.conversationId,",
  "  chatwootBaseUrl: ctx.chatwootBaseUrl,",
  "  wooBaseUrl: ctx.wooBaseUrl,",
  "  shippingApiUrl: ctx.shippingApiUrl,",
  "  defaultItemWeightKg: ctx.defaultItemWeightKg,",
  "  catalog: ctx.catalog,",
  "  senderName: ctx.senderName,",
  "  senderEmail: ctx.senderEmail,",
  "  senderPhone: ctx.senderPhone,",
  "  reply,",
  "  action: resolvedAction,",
  "  orderData: data",
  "};"
].join('\n');

const BUILD_SHIPPING_CODE = [
  "const data = $json;",
  "const items = (data.orderData.items || []).filter(i => i.product_id || i.variation_id);",
  "const cep = String(data.orderData.billing_postcode || '').replace(/\\D/g, '');",
  "// Build items[] payload for the multi-item shipping API",
  "const itemsForApi = items.map(i => {",
  "  const out = { qty: Math.max(1, Number(i.quantity || 1)) };",
  "  if (i.variation_id) out.variation_id = Number(i.variation_id);",
  "  else if (i.product_id) out.product_id = Number(i.product_id);",
  "  return out;",
  "});",
  "const params = [];",
  "if (cep) params.push('cep=' + encodeURIComponent(cep));",
  "if (itemsForApi.length > 0) params.push('items=' + encodeURIComponent(JSON.stringify(itemsForApi)));",
  "const ready = Boolean(cep.length === 8 && itemsForApi.length > 0);",
  "const url = ready ? data.shippingApiUrl + '?' + params.join('&') : '';",
  "return { ...data, shippingQuoteUrl: url, shippingQuoteReady: ready };"
].join('\n');

const FILL_PREVIEW_CODE = [
  "const parsed = $('Parse AI Response').first().json;",
  "const shippingResp = $input.first().json || {};",
  "const parseBody = v => {",
  "  if (v && typeof v === 'object') return v;",
  "  if (typeof v === 'string') { try { return JSON.parse(v); } catch (e) { return {}; } }",
  "  return {};",
  "};",
  "const respBody = parseBody(shippingResp.body || shippingResp);",
  "const parseMoney = v => {",
  "  if (typeof v === 'number') return Number.isFinite(v) ? v : 0;",
  "  const s = String(v || '').replace(/[^0-9,.\\-]/g, '').trim();",
  "  if (!s) return 0;",
  "  const norm = s.includes(',') && s.includes('.') ? s.replace(/\\./g,'').replace(',', '.') : s.replace(',', '.');",
  "  const n = Number.parseFloat(norm);",
  "  return Number.isFinite(n) ? n : 0;",
  "};",
  "const firstText = function() {",
  "  for (let i = 0; i < arguments.length; i++) {",
  "    const x = arguments[i];",
  "    if (x === null || x === undefined) continue;",
  "    if (typeof x === 'string' && x.trim()) return x.trim();",
  "    if (typeof x === 'number') return String(x);",
  "  }",
  "  return '';",
  "};",
  "const methodTitle = m => {",
  "  const s = (m && typeof m.settings === 'object') ? m.settings : {};",
  "  const isn = (m && typeof m.instance_settings === 'object') ? m.instance_settings : {};",
  "  return firstText((m && m.custom_title), s.custom_title, isn.custom_title, (m && m.method_title), s.title, isn.title, (m && m.title), (m && m.label), (m && m.name));",
  "};",
  "const methodLabel = m => {",
  "  const title = methodTitle(m);",
  "  const id = String((m && (m.id || m.method_id)) || '').trim();",
  "  if (title && id && id.toLowerCase() !== title.toLowerCase()) return title + ' (' + id + ')';",
  "  return title || id || 'Frete';",
  "};",
  "const methodPrice = m => parseMoney(firstText((m && m.total), (m && m.cost), (m && m.price), (m && m.rate), (m && m.value)));",
  "const methodDays = m => firstText((m && m.days), (m && m.delivery_days), (m && m.delivery_time), (m && m.deadline), (m && m.estimate), (m && m.eta));",
  "",
  "const methodsDebug = Array.isArray(respBody.methods_debug) ? respBody.methods_debug : [];",
  "const chosenRateId = String((Array.isArray(respBody.chosen_methods) ? respBody.chosen_methods[0] : '') || '').trim();",
  "const cmParts = chosenRateId.split(':');",
  "const chosenMethodId = cmParts[0];",
  "const chosenInstanceId = cmParts[1];",
  "let chosen = null;",
  "if (chosenRateId && methodsDebug.length > 0) {",
  "  chosen = methodsDebug.find(m => String(m.id || '').trim() === chosenMethodId && (!chosenInstanceId || String(m.instance_id || '').trim() === chosenInstanceId)) || methodsDebug.find(m => String(m.id || '').trim() === chosenMethodId) || null;",
  "}",
  "const topLevelRaw = firstText(respBody.shipping_total, respBody.shippingTotal, respBody.total_shipping, (respBody.totals && respBody.totals.shipping_total), (respBody.totals && respBody.totals.shipping), (respBody.selected_rate && respBody.selected_rate.total), (respBody.selected_rate && respBody.selected_rate.cost), (respBody.chosen_rate && respBody.chosen_rate.total), (respBody.chosen_rate && respBody.chosen_rate.cost));",
  "const topLevelPrice = parseMoney(topLevelRaw);",
  "const topLevelHas = topLevelRaw !== '' && topLevelRaw !== null && topLevelRaw !== undefined;",
  "if (!chosen && topLevelHas) {",
  "  chosen = {",
  "    id: firstText((respBody.selected_rate && respBody.selected_rate.method_id), (respBody.chosen_rate && respBody.chosen_rate.method_id), chosenMethodId, ''),",
  "    custom_title: methodTitle(respBody.selected_rate) || methodTitle(respBody.chosen_rate),",
  "    total: topLevelPrice",
  "  };",
  "}",
  "if (!chosen && methodsDebug.length > 0) {",
  "  const cands = methodsDebug.map(m => ({ m, p: methodPrice(m), has: m && (m.total != null || m.cost != null || m.price != null || m.rate != null) })).filter(x => x.has);",
  "  chosen = cands.sort((a,b) => a.p - b.p)[0] && cands.sort((a,b) => a.p - b.p)[0].m;",
  "}",
  "const directPrice = methodPrice(chosen);",
  "const directHas = chosen && (chosen.total != null || chosen.cost != null || chosen.price != null || chosen.rate != null);",
  "const resolvedPrice = directHas ? directPrice : topLevelPrice;",
  "const haveResult = chosen && (directHas || topLevelHas);",
  "const options = haveResult ? [{ name: methodLabel(chosen), price: resolvedPrice, days: methodDays(chosen), is_free: resolvedPrice === 0 }] : [];",
  "",
  "const data = parsed.orderData;",
  "const items = data.items || [];",
  "const catalog = parsed.catalog || [];",
  "const fmt = n => 'R$ ' + Number(n).toFixed(2).replace('.', ',');",
  "",
  "const lineRows = items.map(i => {",
  "  const match = catalog.find(p => {",
  "    if (i.variation_id) return Number(p.variation_id) === Number(i.variation_id);",
  "    if (i.product_id) return Number(p.product_id) === Number(i.product_id);",
  "    return false;",
  "  });",
  "  const refId = i.variation_id || i.product_id;",
  "  const title = (match && match.title) || ('Produto #' + refId);",
  "  const price = Number(String((match && match.price) || 0).replace(/[^0-9.,-]/g,'').replace(',', '.')) || 0;",
  "  const qty = Math.max(1, Number(i.quantity || 1));",
  "  return { title, qty, price, lineTotal: price * qty };",
  "});",
  "const subtotal = lineRows.reduce((s, r) => s + r.lineTotal, 0);",
  "const itemsBlock = lineRows.map(r => '• ' + r.title + ' — ' + r.qty + 'x — ' + fmt(r.lineTotal)).join('\\n');",
  "",
  "const addressBlock = [",
  "  ['Email', data.billing_email],",
  "  ['CEP', data.billing_postcode],",
  "  ['Endereço', data.billing_address_1],",
  "  ['Número', data.billing_number],",
  "  ['Bairro', data.billing_neighborhood],",
  "  ['Cidade', data.billing_city],",
  "  ['Estado (UF)', data.billing_state],",
  "  ['CPF', data.billing_cpf],",
  "  ['Telefone', data.billing_phone]",
  "].filter(p => String(p[1] || '').trim()).map(p => p[0] + ': ' + String(p[1]).trim()).join('\\n');",
  "",
  "const shippingLine = options.length > 0",
  "  ? 'Frete: ' + options[0].name + ' - ' + (options[0].is_free ? 'GRÁTIS' : fmt(options[0].price)) + (options[0].days ? ' (' + options[0].days + ' dias úteis)' : '')",
  "  : 'Frete: a calcular — confirme e enviaremos o valor antes do pagamento';",
  "const shippingPrice = options.length > 0 ? options[0].price : 0;",
  "const totalLine = options.length > 0 ? 'Total: ' + fmt(subtotal + shippingPrice) : '';",
  "",
  "const previewBody = [",
  "  '📦 *Itens*', itemsBlock, '',",
  "  '📍 *Entrega*', addressBlock, '',",
  "  '🚚 *Frete*', shippingLine, '',",
  "  '💰 *Resumo*', 'Subtotal: ' + fmt(subtotal), totalLine",
  "].filter(Boolean).join('\\n');",
  "",
  "const firstName = String(data.billing_name || parsed.senderName || '').trim().split(/\\s+/)[0] || '';",
  "const greeting = firstName ? ('Perfeito, ' + firstName + '!') : 'Perfeito!';",
  "const closing = options.length > 0",
  "  ? 'Posso confirmar e gerar o link de pagamento? Responda *sim* para prosseguir.'",
  "  : 'Posso prosseguir? Responda *sim* para gerar o link de pagamento.';",
  "",
  "const reply = [greeting + ' Aqui está o resumo do seu pedido:', '', previewBody, '', closing].join('\\n');",
  "",
  "return {",
  "  accountId: parsed.accountId,",
  "  conversationId: parsed.conversationId,",
  "  chatwootBaseUrl: parsed.chatwootBaseUrl,",
  "  reply,",
  "  chosenShipping: options.length > 0 ? {",
  "    method_id: String((chosen && chosen.id) || chosenMethodId || 'flat_rate'),",
  "    method_label: options[0].name,",
  "    cost: options[0].price",
  "  } : null",
  "};"
].join('\n');

const BUILD_ORDER_SHIP_CODE = [
  "const data = $json;",
  "const items = (data.orderData.items || []).filter(i => i.product_id || i.variation_id);",
  "const cep = String(data.orderData.billing_postcode || '').replace(/\\D/g, '');",
  "const itemsForApi = items.map(i => {",
  "  const out = { qty: Math.max(1, Number(i.quantity || 1)) };",
  "  if (i.variation_id) out.variation_id = Number(i.variation_id);",
  "  else if (i.product_id) out.product_id = Number(i.product_id);",
  "  return out;",
  "});",
  "const params = [];",
  "if (cep) params.push('cep=' + encodeURIComponent(cep));",
  "if (itemsForApi.length > 0) params.push('items=' + encodeURIComponent(JSON.stringify(itemsForApi)));",
  "const ready = Boolean(cep.length === 8 && itemsForApi.length > 0);",
  "const url = ready ? data.shippingApiUrl + '?' + params.join('&') : '';",
  "return { ...data, orderShippingQuoteUrl: url, orderShippingQuoteReady: ready };"
].join('\n');

const RESOLVE_SHIP_CODE = [
  "const parsed = $('Parse AI Response').first().json;",
  "const shippingResp = $input.first().json || {};",
  "const parseBody = v => {",
  "  if (v && typeof v === 'object') return v;",
  "  if (typeof v === 'string') { try { return JSON.parse(v); } catch (e) { return {}; } }",
  "  return {};",
  "};",
  "const respBody = parseBody(shippingResp.body || shippingResp);",
  "const parseMoney = v => {",
  "  if (typeof v === 'number') return Number.isFinite(v) ? v : 0;",
  "  const s = String(v || '').replace(/[^0-9,.\\-]/g, '').trim();",
  "  if (!s) return 0;",
  "  const norm = s.includes(',') && s.includes('.') ? s.replace(/\\./g,'').replace(',', '.') : s.replace(',', '.');",
  "  const n = Number.parseFloat(norm);",
  "  return Number.isFinite(n) ? n : 0;",
  "};",
  "const firstText = function() {",
  "  for (let i = 0; i < arguments.length; i++) {",
  "    const x = arguments[i];",
  "    if (x === null || x === undefined) continue;",
  "    if (typeof x === 'string' && x.trim()) return x.trim();",
  "    if (typeof x === 'number') return String(x);",
  "  }",
  "  return '';",
  "};",
  "const methodTitle = m => {",
  "  const s = (m && typeof m.settings === 'object') ? m.settings : {};",
  "  const isn = (m && typeof m.instance_settings === 'object') ? m.instance_settings : {};",
  "  return firstText((m && m.custom_title), s.custom_title, isn.custom_title, (m && m.method_title), s.title, isn.title, (m && m.title), (m && m.label), (m && m.name));",
  "};",
  "const methodPrice = m => parseMoney(firstText((m && m.total), (m && m.cost), (m && m.price), (m && m.rate), (m && m.value)));",
  "const methodsDebug = Array.isArray(respBody.methods_debug) ? respBody.methods_debug : [];",
  "const chosenRateId = String((Array.isArray(respBody.chosen_methods) ? respBody.chosen_methods[0] : '') || '').trim();",
  "const cmParts = chosenRateId.split(':');",
  "const chosenMethodId = cmParts[0];",
  "const chosenInstanceId = cmParts[1];",
  "let chosen = null;",
  "if (chosenRateId && methodsDebug.length > 0) {",
  "  chosen = methodsDebug.find(m => String(m.id || '').trim() === chosenMethodId && (!chosenInstanceId || String(m.instance_id || '').trim() === chosenInstanceId)) || methodsDebug.find(m => String(m.id || '').trim() === chosenMethodId) || null;",
  "}",
  "const topLevelPrice = parseMoney(firstText(respBody.shipping_total, respBody.shippingTotal, respBody.total_shipping, (respBody.totals && respBody.totals.shipping_total), (respBody.totals && respBody.totals.shipping), (respBody.selected_rate && respBody.selected_rate.total), (respBody.selected_rate && respBody.selected_rate.cost), (respBody.chosen_rate && respBody.chosen_rate.total), (respBody.chosen_rate && respBody.chosen_rate.cost)));",
  "if (!chosen && topLevelPrice > 0) {",
  "  chosen = { id: firstText((respBody.selected_rate && respBody.selected_rate.method_id), (respBody.chosen_rate && respBody.chosen_rate.method_id), chosenMethodId, ''), custom_title: methodTitle(respBody.selected_rate) || methodTitle(respBody.chosen_rate), total: topLevelPrice };",
  "}",
  "if (!chosen && methodsDebug.length > 0) {",
  "  const sortedM = methodsDebug.map(m => ({ m, p: methodPrice(m) })).filter(x => x.p > 0).sort((a,b) => a.p - b.p);",
  "  chosen = sortedM[0] && sortedM[0].m;",
  "}",
  "const directPrice = methodPrice(chosen);",
  "const cost = directPrice > 0 ? directPrice : topLevelPrice;",
  "const resolvedMethodId = String((chosen && chosen.id) || chosenMethodId || 'flat_rate').trim();",
  "const resolvedMethodTitle = methodTitle(chosen) || resolvedMethodId;",
  "return {",
  "  ...parsed,",
  "  resolvedShipping: {",
  "    method_id: resolvedMethodId,",
  "    method_title: resolvedMethodTitle,",
  "    cost: Number(cost.toFixed(2)),",
  "    label: resolvedMethodTitle + (resolvedMethodId && resolvedMethodId !== resolvedMethodTitle ? ' (' + resolvedMethodId + ')' : '')",
  "  }",
  "};"
].join('\n');

const BUILD_PAYLOAD_CODE = [
  "const parsed = $('Parse AI Response').first().json;",
  "const resolved = $('Resolve Order Shipping').first().json;",
  "// All orders go through as GUEST (customer_id: 0) — never auto-link to existing accounts.",
  "const d = parsed.orderData;",
  "const ship = resolved.resolvedShipping || {};",
  "const lineItems = (d.items || []).map(i => {",
  "  const productId = Number(i.product_id || 0);",
  "  const variationId = Number(i.variation_id || 0);",
  "  const li = { quantity: Math.max(1, Number(i.quantity || 1)) };",
  "  if (productId) li.product_id = productId;",
  "  if (variationId) li.variation_id = variationId;",
  "  return li;",
  "}).filter(li => li.product_id || li.variation_id);",
  "const nameParts = String(d.billing_name || '').trim().split(/\\s+/);",
  "const billing = {",
  "  first_name: nameParts[0] || '',",
  "  last_name: nameParts.slice(1).join(' ') || '',",
  "  email: d.billing_email || '',",
  "  phone: d.billing_phone || '',",
  "  address_1: d.billing_address_1 || '',",
  "  number: d.billing_number || '',",
  "  neighborhood: d.billing_neighborhood || '',",
  "  city: d.billing_city || '',",
  "  state: d.billing_state || '',",
  "  postcode: d.billing_postcode || '',",
  "  country: 'BR',",
  "  cpf: d.billing_cpf || ''",
  "};",
  "const shippingLines = (ship.method_id && Number(ship.cost) >= 0)",
  "  ? [{ method_id: String(ship.method_id), method_title: String(ship.method_title || ship.method_id), total: Number(ship.cost).toFixed(2) }]",
  "  : [];",
  "return {",
  "  ...parsed,",
  "  payload: {",
  "    payment_method: 'pagarme-pix',",
  "    payment_method_title: 'PIX',",
  "    set_paid: false,",
  "    status: 'pending',",
  "    customer_id: 0,",
  "    billing,",
  "    shipping: { ...billing },",
  "    line_items: lineItems,",
  "    shipping_lines: shippingLines,",
  "    meta_data: [",
  "      { key: '_billing_cpf', value: billing.cpf },",
  "      { key: '_billing_number', value: billing.number },",
  "      { key: '_billing_neighborhood', value: billing.neighborhood },",
  "      { key: '_created_via_chatwoot_bot', value: 'fresh-v1' }",
  "    ]",
  "  }",
  "};"
].join('\n');

const BUILD_CONFIRM_CODE = [
  "const parsed = $('Parse AI Response').first().json;",
  "const resp = $input.first().json || {};",
  "const created = resp.body || resp;",
  "let reply = parsed.reply || 'Pedido recebido!';",
  "if (created && created.id) {",
  "  const payUrl = created.payment_url || (created._links && created._links.payment && created._links.payment[0] && created._links.payment[0].href) || '';",
  "  reply += '\\n\\n✅ Pedido *#' + created.id + '* criado com sucesso!';",
  "  if (payUrl) reply += '\\n\\n💳 Para finalizar o pagamento, clique aqui:\\n' + payUrl;",
  "  else reply += '\\n\\nVocê receberá o link de pagamento em instantes.';",
  "",
  "  // ── Save billing to workflow memory, keyed by phone (fallback: email) ──",
  "  // Next conversation with this contact will see previousBilling automatically.",
  "  try {",
  "    const od = parsed.orderData || {};",
  "    const phoneDigits = String(parsed.senderPhone || '').replace(/\\D/g, '').slice(-10);",
  "    const email = String(parsed.senderEmail || '').trim().toLowerCase();",
  "    const memoryKey = (phoneDigits && phoneDigits.length >= 8)",
  "      ? ('p:' + phoneDigits)",
  "      : (email ? ('e:' + email) : '');",
  "    if (memoryKey) {",
  "      const sd = $getWorkflowStaticData('global');",
  "      if (!sd.billingMemory) sd.billingMemory = {};",
  "      sd.billingMemory[memoryKey] = {",
  "        billing_name: od.billing_name || '',",
  "        billing_email: od.billing_email || '',",
  "        billing_phone: od.billing_phone || '',",
  "        billing_cpf: od.billing_cpf || '',",
  "        billing_postcode: od.billing_postcode || '',",
  "        billing_address_1: od.billing_address_1 || '',",
  "        billing_number: od.billing_number || '',",
  "        billing_neighborhood: od.billing_neighborhood || '',",
  "        billing_city: od.billing_city || '',",
  "        billing_state: od.billing_state || '',",
  "        saved_at: new Date().toISOString(),",
  "        last_order_id: created.id",
  "      };",
  "    }",
  "  } catch (e) { /* memory write failed — non-fatal */ }",
  "} else {",
  "  const errMsg = (created && (created.message || created.code)) || '';",
  "  reply += '\\n\\n⚠️ Tive um problema ao gerar o pedido' + (errMsg ? ' (' + errMsg + ')' : '') + '. Um atendente irá ajudar você em instantes.';",
  "}",
  "return {",
  "  accountId: parsed.accountId,",
  "  conversationId: parsed.conversationId,",
  "  chatwootBaseUrl: parsed.chatwootBaseUrl,",
  "  reply",
  "};"
].join('\n');

const PASS_THRU_CODE = [
  "const p = $json;",
  "let reply = String(p.reply || '').trim();",
  "if (!reply) reply = 'Olá! Como posso ajudar?';",
  "return {",
  "  accountId: p.accountId,",
  "  conversationId: p.conversationId,",
  "  chatwootBaseUrl: p.chatwootBaseUrl,",
  "  reply",
  "};"
].join('\n');

// ─────────── Build node objects ───────────
function node(name, type, typeVersion, position, parameters, extras) {
  return Object.assign({
    parameters,
    type,
    typeVersion,
    position,
    id: require('crypto').randomUUID(),
    name
  }, extras || {});
}

const nodes = [
  node('Webhook', 'n8n-nodes-base.webhook', 2, [-2700, 0], {
    httpMethod: 'POST',
    path: 'chatwoot-ai-agent',
    options: {}
  }, { webhookId: 'f7e96fa9-b2b4-406a-915d-7370d94e1e13' }),

  node('Normalize Event', 'n8n-nodes-base.code', 2, [-2440, 0], {
    jsCode: NORMALIZE_CODE
  }),

  node('Should Process?', 'n8n-nodes-base.if', 2.2, [-2180, 0], {
    conditions: {
      options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 },
      conditions: [{
        id: 'cond-process',
        leftValue: '={{ $json.route }}',
        rightValue: 'process',
        operator: { type: 'string', operation: 'equals' }
      }],
      combinator: 'and'
    },
    options: {}
  }),

  node('Get Conversation', 'n8n-nodes-base.httpRequest', 4.2, [-1920, 0], {
    url: "={{ $('Normalize Event').first().json.config.chatwootBaseUrl }}/api/v1/accounts/{{ $('Normalize Event').first().json.accountId }}/conversations/{{ $('Normalize Event').first().json.conversationId }}/messages",
    authentication: 'genericCredentialType',
    genericAuthType: 'httpHeaderAuth',
    sendHeaders: true,
    headerParameters: { parameters: [{ name: 'accept', value: 'application/json' }] },
    options: {}
  }, {
    credentials: { httpHeaderAuth: CRED.chatwoot }
  }),

  node('Get Catalog', 'n8n-nodes-base.googleSheets', 4.5, [-1660, 0], {
    documentId: { __rl: true, value: SHEET_ID, mode: 'id' },
    sheetName: { __rl: true, value: SHEET_TAB, mode: 'name' },
    options: {}
  }, {
    credentials: { googleSheetsOAuth2Api: CRED.googleSheets }
  }),

  node('Maybe Lookup Order', 'n8n-nodes-base.httpRequest', 4.2, [-1400, 0], {
    url: "={{ (() => { const c = $('Normalize Event').first().json; const base = String(c.config.wooBaseUrl||'').replace(/\\/$/, ''); const id = String(c.detectedOrderId||'').trim(); const email = encodeURIComponent(String(c.senderEmail||'').trim()); if (id) return `${base}/wp-json/wc/v3/orders/${id}`; if (email) return `${base}/wp-json/wc/v3/orders?search=${email}&per_page=5&orderby=date&order=desc`; return `${base}/wp-json/wc/v3/orders?per_page=1`; })() }}",
    authentication: 'genericCredentialType',
    genericAuthType: 'httpBasicAuth',
    sendHeaders: true,
    headerParameters: { parameters: [{ name: 'accept', value: 'application/json' }] },
    options: { response: { response: { fullResponse: true, neverError: true } } }
  }, {
    credentials: { httpBasicAuth: CRED.fvStore }
  }),

  node('Build AI Request', 'n8n-nodes-base.code', 2, [-1140, 0], {
    jsCode: BUILD_AI_CODE
  }),

  node('OpenAI Reply', 'n8n-nodes-base.httpRequest', 4.2, [-880, 0], {
    method: 'POST',
    url: 'https://api.openai.com/v1/chat/completions',
    authentication: 'genericCredentialType',
    genericAuthType: 'httpBearerAuth',
    sendHeaders: true,
    headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
    sendBody: true,
    specifyBody: 'json',
    jsonBody: '={{ $json.openAiRequest }}',
    options: { response: { response: { fullResponse: true, neverError: true } } }
  }, {
    credentials: { httpBearerAuth: CRED.openai }
  }),

  node('Parse AI Response', 'n8n-nodes-base.code', 2, [-620, 0], {
    jsCode: PARSE_AI_CODE
  }),

  node('Need Shipping Calc?', 'n8n-nodes-base.if', 2.2, [-360, 0], {
    conditions: {
      options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 },
      conditions: [{
        id: 'cond-ship',
        leftValue: '={{ $json.action }}',
        rightValue: 'calculate_shipping',
        operator: { type: 'string', operation: 'equals' }
      }],
      combinator: 'and'
    },
    options: {}
  }),

  node('Build Shipping Request', 'n8n-nodes-base.code', 2, [-100, 220], {
    jsCode: BUILD_SHIPPING_CODE
  }),

  node('Get Shipping Quote', 'n8n-nodes-base.httpRequest', 4.2, [180, 220], {
    url: '={{ $json.shippingQuoteUrl }}',
    options: { response: { response: { fullResponse: true, neverError: true } } }
  }),

  node('Fill Preview', 'n8n-nodes-base.code', 2, [460, 220], {
    jsCode: FILL_PREVIEW_CODE
  }),

  node('Create Order?', 'n8n-nodes-base.if', 2.2, [-100, 0], {
    conditions: {
      options: { caseSensitive: true, leftValue: '', typeValidation: 'strict', version: 2 },
      conditions: [{
        id: 'cond-create',
        leftValue: '={{ $json.action }}',
        rightValue: 'create_order',
        operator: { type: 'string', operation: 'equals' }
      }],
      combinator: 'and'
    },
    options: {}
  }),

  node('Build Order Shipping Request', 'n8n-nodes-base.code', 2, [180, -220], {
    jsCode: BUILD_ORDER_SHIP_CODE
  }),

  node('Get Order Shipping Quote', 'n8n-nodes-base.httpRequest', 4.2, [460, -220], {
    url: '={{ $json.orderShippingQuoteUrl }}',
    options: { response: { response: { fullResponse: true, neverError: true } } }
  }),

  node('Resolve Order Shipping', 'n8n-nodes-base.code', 2, [740, -220], {
    jsCode: RESOLVE_SHIP_CODE
  }),

  node('Build Order Payload', 'n8n-nodes-base.code', 2, [1020, -220], {
    jsCode: BUILD_PAYLOAD_CODE
  }),

  node('Woo Create Order', 'n8n-nodes-base.httpRequest', 4.2, [1300, -220], {
    method: 'POST',
    url: "={{ $('Parse AI Response').first().json.wooBaseUrl + '/wp-json/wc/v3/orders/' }}",
    authentication: 'genericCredentialType',
    genericAuthType: 'httpBasicAuth',
    sendHeaders: true,
    headerParameters: { parameters: [
      { name: 'accept', value: 'application/json' },
      { name: 'content-type', value: 'application/json' }
    ]},
    sendBody: true,
    specifyBody: 'json',
    jsonBody: '={{ $json.payload }}',
    options: { response: { response: { fullResponse: true, neverError: true } } }
  }, {
    credentials: { httpBasicAuth: CRED.fvStore }
  }),

  node('Build Order Confirmation', 'n8n-nodes-base.code', 2, [1580, -220], {
    jsCode: BUILD_CONFIRM_CODE
  }),

  node('Plain Reply Pass-through', 'n8n-nodes-base.code', 2, [180, 220 + 220], {
    jsCode: PASS_THRU_CODE
  }),

  node('Send Reply', 'n8n-nodes-base.httpRequest', 4.2, [1300, 220], {
    method: 'POST',
    url: '={{ $json.chatwootBaseUrl }}/api/v1/accounts/{{ $json.accountId }}/conversations/{{ $json.conversationId }}/messages',
    authentication: 'genericCredentialType',
    genericAuthType: 'httpHeaderAuth',
    sendHeaders: true,
    headerParameters: { parameters: [{ name: 'Content-Type', value: 'application/json' }] },
    sendBody: true,
    specifyBody: 'json',
    jsonBody: "={{ { content: $json.reply, message_type: 'outgoing', private: false, content_type: 'text' } }}",
    options: {}
  }, {
    credentials: { httpHeaderAuth: CRED.chatwoot }
  })
];

// ─────────── Connections ───────────
const link = (from, to, idxFrom = 0) => ({
  [from]: {
    main: [
      ...(idxFrom > 0 ? Array(idxFrom).fill([]) : []),
      [{ node: to, type: 'main', index: 0 }]
    ]
  }
});
const linkMulti = (from, ...targets) => ({
  [from]: {
    main: targets.map(t => Array.isArray(t) ? t.map(n => ({ node: n, type: 'main', index: 0 })) : [{ node: t, type: 'main', index: 0 }])
  }
});

const connections = Object.assign(
  link('Webhook', 'Normalize Event'),
  link('Normalize Event', 'Should Process?'),
  // Should Process: true → Get Conversation, false → end
  { 'Should Process?': { main: [[{ node: 'Get Conversation', type: 'main', index: 0 }]] } },
  link('Get Conversation', 'Get Catalog'),
  link('Get Catalog', 'Maybe Lookup Order'),
  link('Maybe Lookup Order', 'Build AI Request'),
  link('Build AI Request', 'OpenAI Reply'),
  link('OpenAI Reply', 'Parse AI Response'),
  link('Parse AI Response', 'Need Shipping Calc?'),
  // Need Shipping Calc: true → Build Shipping Request, false → Create Order?
  { 'Need Shipping Calc?': { main: [
    [{ node: 'Build Shipping Request', type: 'main', index: 0 }],
    [{ node: 'Create Order?', type: 'main', index: 0 }]
  ]}},
  link('Build Shipping Request', 'Get Shipping Quote'),
  link('Get Shipping Quote', 'Fill Preview'),
  link('Fill Preview', 'Send Reply'),
  // Create Order: true → Build Order Shipping Request, false → Plain Reply Pass-through
  { 'Create Order?': { main: [
    [{ node: 'Build Order Shipping Request', type: 'main', index: 0 }],
    [{ node: 'Plain Reply Pass-through', type: 'main', index: 0 }]
  ]}},
  link('Build Order Shipping Request', 'Get Order Shipping Quote'),
  link('Get Order Shipping Quote', 'Resolve Order Shipping'),
  link('Resolve Order Shipping', 'Build Order Payload'),
  link('Build Order Payload', 'Woo Create Order'),
  link('Woo Create Order', 'Build Order Confirmation'),
  link('Build Order Confirmation', 'Send Reply'),
  link('Plain Reply Pass-through', 'Send Reply')
);

const workflow = {
  name: 'Chatwoot n8n AI support Agent v16',
  nodes,
  pinData: {},
  connections,
  active: false,
  settings: { executionOrder: 'v1' },
  versionId: require('crypto').randomUUID(),
  meta: { templateCredsSetupCompleted: true },
  id: require('crypto').randomUUID().replace(/-/g, '').slice(0, 16),
  tags: []
};

const outPath = 'F:\\github\\chatwoot n8n ai agent new version\\Chatwoot_n8n_AI_Support_Agent_v16.json';
fs.writeFileSync(outPath, JSON.stringify(workflow, null, 2), 'utf-8');
console.log('Wrote ' + outPath);
console.log('Nodes: ' + nodes.length);
console.log('Connections: ' + Object.keys(connections).length);
